# Generated by Django 5.2.12 on 2026-04-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="summary",
            name="analysis",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="summary",
            name="key_points",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="summary",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]

