# Generated by Django 5.2.12 on 2026-04-02 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0002_summary_insights_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="summary",
            name="analysis",
        ),
        migrations.RemoveField(
            model_name="summary",
            name="key_points",
        ),
        migrations.RemoveField(
            model_name="summary",
            name="notes",
        ),
    ]

